// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcFJdrUSSnQtvVE1PpWUfTglqmf-FN5po',
    appId: '1:516852975421:web:deed026a306d0ae7e86754',
    messagingSenderId: '516852975421',
    projectId: 'spendify-98bb2',
    authDomain: 'spendify-98bb2.firebaseapp.com',
    storageBucket: 'spendify-98bb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwSbOYDcJjkQAvjslIPrCT-MG5HZawjh0',
    appId: '1:516852975421:android:a2f39d825ad6de44e86754',
    messagingSenderId: '516852975421',
    projectId: 'spendify-98bb2',
    storageBucket: 'spendify-98bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXI9BvKDdN_qK3Ux_1P9AjQ6Oxxx7q6jA',
    appId: '1:516852975421:ios:6be0ed7d188b5151e86754',
    messagingSenderId: '516852975421',
    projectId: 'spendify-98bb2',
    storageBucket: 'spendify-98bb2.firebasestorage.app',
    iosBundleId: 'com.example.spendify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXI9BvKDdN_qK3Ux_1P9AjQ6Oxxx7q6jA',
    appId: '1:516852975421:ios:6be0ed7d188b5151e86754',
    messagingSenderId: '516852975421',
    projectId: 'spendify-98bb2',
    storageBucket: 'spendify-98bb2.firebasestorage.app',
    iosBundleId: 'com.example.spendify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcFJdrUSSnQtvVE1PpWUfTglqmf-FN5po',
    appId: '1:516852975421:web:01d0770a953d0dbce86754',
    messagingSenderId: '516852975421',
    projectId: 'spendify-98bb2',
    authDomain: 'spendify-98bb2.firebaseapp.com',
    storageBucket: 'spendify-98bb2.firebasestorage.app',
  );
}
